# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-24 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attractiveness', models.FloatField()),
                ('intelligenceLevel', models.FloatField()),
                ('isCommitted', models.BooleanField(default=False)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=13)),
                ('attractionRequirement', models.FloatField()),
                ('boyType', models.IntegerField(choices=[(1, 'The Miser'), (2, 'The Generous'), (3, 'The Geek')], default=None)),
            ],
        ),
        migrations.CreateModel(
            name='EssentialGift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giftID', models.PositiveIntegerField()),
                ('exchangeTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('giftType', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attractiveness', models.FloatField()),
                ('intelligenceLevel', models.FloatField()),
                ('isCommitted', models.BooleanField(default=False)),
                ('maintenanceBudget', models.DecimalField(decimal_places=2, max_digits=13)),
                ('datingCriteria', models.IntegerField(choices=[(1, 'Most Attractive'), (2, 'Most Rich'), (3, 'Most Intelligent')])),
                ('girlType', models.IntegerField(choices=[(1, 'The Choosy'), (2, 'The Normal'), (3, 'The Desperate')], default=None)),
            ],
        ),
        migrations.CreateModel(
            name='LuxuryGift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('value', models.FloatField()),
                ('luxuryRating', models.FloatField()),
                ('difficultyToObtain', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('breakupOn', models.DateTimeField(default=None)),
                ('boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vDate.Girl')),
                ('girl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vDate.Boy')),
            ],
        ),
        migrations.CreateModel(
            name='UtilityGift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('value', models.FloatField()),
                ('utilityValue', models.FloatField()),
                ('utilityClass', models.IntegerField(choices=[(1, 'Health'), (2, 'Home'), (3, 'Kitchen'), (4, 'Sanitation'), (5, 'Stationary')])),
            ],
        ),
        migrations.AddField(
            model_name='exchange',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='vDate.Relation'),
        ),
    ]
