# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-24 10:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vDate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boy',
            name='attractionRequirement',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='boy',
            name='attractiveness',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='boy',
            name='intelligenceLevel',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='girl',
            name='attractiveness',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='girl',
            name='intelligenceLevel',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='relation',
            name='boy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vDate.Boy'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='breakupOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='girl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vDate.Girl'),
        ),
    ]
