# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vDate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attractivenes', models.FloatField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=13)),
                ('intelligenceLevel', models.FloatField()),
                ('attractionRequirement', models.FloatField()),
                ('isCommitted', models.BooleanField(default=False)),
                ('boyType', models.IntegerField(choices=[(1, 'The Miser'), (2, 'The Generous'), (3, 'The Geek')], default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='girl',
            name='girlType',
            field=models.IntegerField(choices=[(1, 'The Choosy'), (2, 'The Normal'), (3, 'The Desperate')], default=None),
        ),
        migrations.AddField(
            model_name='girl',
            name='isCommitted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EssentialGift',
            fields=[
                ('gift_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vDate.Gift')),
            ],
            bases=('vDate.gift',),
        ),
        migrations.CreateModel(
            name='LuxuryGift',
            fields=[
                ('gift_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vDate.Gift')),
                ('luxuryRating', models.FloatField()),
                ('difficultyToObtain', models.FloatField()),
            ],
            bases=('vDate.gift',),
        ),
        migrations.CreateModel(
            name='UtilityGift',
            fields=[
                ('gift_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vDate.Gift')),
                ('utilityValue', models.FloatField()),
                ('utilityClass', models.IntegerField(choices=[(1, 'Health'), (2, 'Home'), (3, 'Kitchen'), (4, 'Sanitation'), (5, 'Stationary')])),
            ],
            bases=('vDate.gift',),
        ),
    ]
