# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vDate', '0002_auto_20170220_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift', to='vDate.Gift')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boyfriend', to='vDate.Boy', unique=True)),
                ('girl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='girlfriend', to='vDate.Girl', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='exchanges',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='vDate.Relation'),
        ),
    ]
