# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-26 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vDate', '0002_auto_20170224_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='compatibility',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exchange',
            name='giftType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
