# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-26 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vDate', '0003_auto_20170226_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='compatibility',
            field=models.FloatField(default=0),
        ),
    ]
